# Generated by Django 5.1.1 on 2024-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_toy_release_data_toy_was_included_in_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='toy',
            name='release_data',
            field=models.DateTimeField(default='2024-10-05'),
        ),
    ]
