# Generated by Django 5.1.1 on 2024-10-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_alter_toy_options_alter_toy_release_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='release_data',
            field=models.DateTimeField(),
        ),
    ]
